export HISTFILE=~/.histfile
export HISTSIZE=50000
export SAVEHIST=50000

setopt appendhistory

export EDITOR="vim"
export BROWSER='firefox'

BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL


[[ -f ~/.dircolors ]] && \
  source <(dircolors ~/.dircolors)

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*:processes' command 'ps -aeu'
zstyle ':completion:*:processes-names' command 'ps -e o cmd|tail -n +2'

zstyle ':completion:*' completer _expand _complete _correct _approximate _ignored

zstyle ':completion:*' max-errors 1

zstyle ':completion:*' matcher-list  'm:{a-zA-Z}={A-Za-z}'

zstyle ':completion:*' ignore-parents pwd

zstyle ':completion:*:ssh:*' menu select

zstyle ':completion:*' menu select
zstyle ':completion:*' select-prompt %m %p %s

zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches :('

fpath=(~/.zsh/completion $fpath) 
autoload -Uz compinit
compinit
setopt correct

setopt hist_ignore_all_dups

bindkey '^[[7~' beginning-of-line
bindkey '^[[8~' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[[5~' up-history
bindkey '^[[6~' down-history

#terminaali
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line

bindkey '^[OH' beginning-of-line
bindkey '^[OF' end-of-line


alias ls="ls --color=auto"
alias bc="bc -l"
alias cal="cal -m3"
alias pdf="epdfview"
alias youtube="youtube-dl --no-playlist -r 100K"

export PATH=~/.cabal/bin:$PATH
export PATH=.cabal-sandbox/bin:$PATH
export PATH=$PATH:/usr/local/sbin/:~/bin
export PATH=$PATH:/usr/bin/
export PATH=$PATH:~/bin/
export PATH=$PATH:~/.local/bin

export PYTHONPATH=$PYTHONPATH:~/.local

autoload colors zsh/terminfo
if [[ "$terminfo[colors]" -ge 8 ]]; then
    colors
fi
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
    eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
    eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
    (( count = $count + 1 ))
done

PR_NO_COLOUR="%{$terminfo[sgr0]%}"
if [[ "$USERNAME" = "root" ]]; then PR_USERCOLOR=$PR_RED; else PR_USERCOLOR=$PR_GREEN; fi

if [[ -z $SSH_CONNECTION ]]; then PR_HOSTCOLOR=$PR_GREEN; else PR_HOSTCOLOR=$PR_RED; fi

PS1=''$PR_CYAN'['$PR_USERCOLOR'%n'$PR_YELLOW'@'$PR_HOSTCOLOR'%M'$PR_CYAN'] '$PR_GREEN'('$PR_BLUE'%?'$PR_GREEN') '$PR_GREEN'%~ '$PR_LIGHT_CYAN'$'$PR_NO_COLOUR' '

alias ja_lc='export LANG="ja_JP.UTF-8"; export LC_ALL="ja_JP.UTF-8"'
alias kr_lc='export LANG="ko_KR.UTF-8"; export LC_ALL="ko_KR.UTF-8"'

stty stop ''
stty start ''
stty -ixon
stty -ixoff

bindkey -v

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

export ncpus=8

export PGDATA=/usr/lib/pgsql/data
export LD_LIBRARY_PATH=/usr/lib/nvidia:/usr/lib32/nvidia:$LD_LIBRARY_PATH

if [[ -n $RUN_IRC ]] then
	ssh evo
fi

#if [[ -n $RUN_RTORRENT ]] then
#	cd /media/disk/anime && rtorrent
#fi

if [[ -n $RUN_GIZLO ]] then
	cd ~/gizlo-backend
fi
if [[ -n $RUN_GIZLO_DASHBOARD ]] then
	cd ~/gizlo-admin
fi

if [[ -n $RUN_POSTGRES ]] then
	sudo su postgres
fi

alias monstercat="livestreamer 'http://www.twitch.tv/monstercat' best"

alias hyster="livestreamer 'rtmp://zergling.dy.fi/live/hyster live=1 swfVfy=http://zergling.dy.fi/jwplayer/player.swf' best"
alias yuizy="livestreamer 'rtmp://zergling.dy.fi/live/yuizy live=1 swfVfy=http://zergling.dy.fi/jwplayer/player.swf' best"

export NVM_DIR="/home/santtu/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export ELM_HOME=~/.nvm/versions/node/v0.12.4/lib/node_modules/elm/share
