set nocompatible               " be iMproved

filetype plugin indent on     " required! 

nmap <Leader>u :so /home/santtu/.vimrc<cr>

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. <Leader>aip)
nmap <Leader>o <Plug>(EasyAlign)
let g:easy_align_delimiters = {
\ ':': { 'pattern': '::' },
\ '<': { 'pattern': '-<' },
\ '>': { 'pattern': '->' },
\ '-': { 'pattern': '-<' }
\}

"shim
let g:shim_ghciInterp = "cabal exec ghci"

syntax enable
set background=dark
let base16colorspace=256
colorscheme base16-default

hi Normal ctermbg=none

set nowrap
set nu
set history=1000
set hlsearch
"set mouse=a

set scrolloff=8
set sidescrolloff=0
set sidescroll=0
set backspace=indent,eol,start " Allow backspecing over everything in insert mode

set ignorecase
"set smartcase

set tabstop=2
set shiftwidth=2
"set smarttab " Smart tabbing
set expandtab
"autocmd BufRead,BufNewFile   *.rb,*.slim,*.js set shiftwidth=2

set cindent
set cinoptions=g-1 " public: private: protected: no indent

"tabcomplete
set wildignorecase
set wildmode=longest,list,full
set wildmenu

"set iskeyword-=_

if has("unix")
    set backup
    set backupdir=/tmp
    set directory=/tmp
elseif has("win32")
    set backup
    set backupdir=C:\Windows\Temp
    set noswapfile
endif

"Key mappings
let mapleader = "\\"

no Q <Nop>

no + :cn<cr>
no - :cp<cr>

no <leader><space> :noh<cr>

noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-h> <C-w>h
noremap <C-l> <C-w>l


set pastetoggle=<F4>

