setxkbmap dvorak
xmodmap ~/.Xmodmap
key_repeat.zsh
xrdb ~/.Xresources

pulseaudio --start &

session() {
  exec dbus-launch --exit-with-session "${@}"
}

cd
case "$2" in
  gnome)
    exec gnome-session ;;
  steam)
    openbox &
    nitrogen --restore
    session steam ;;
  xbmc)
    session "$2" ;;
  xmonad)
    session "$2" ;;
  *)
    nitrogen --restore
    session "${2:-xmonad}" ;;
esac
