export GTK_IM_MODULE=scim
export XMODIFIERS=@im=SCIM
export QT_IM_MODULE=scim

scim -d

setxkbmap dvorak
xmodmap ~/.Xmodmap

pulseaudio --start &

xrandr --setprovideroutputsource modesetting NVIDIA-0
set_displays.zsh

random_wallpapers

xrdb ~/.Xresources

session() {
  exec dbus-launch --exit-with-session "${@}"
}

cd
case "$2" in
  gnome)
    exec gnome-session ;;
  steam)
    openbox &
    session steam ;;
  xbmc)
    session "$2" ;;
  xmonad)
    session "$2" ;;
  *)
    session "${2:-xmonad}" ;;
esac

